# Generated by Django 3.2.9 on 2022-01-11 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bubba', '0002_bubbs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bubbs',
            new_name='Bubbas',
        ),
    ]
